// Generated from the reset local Supabase schema; migrations remain authoritative.
import { bigint, boolean, date, integer, jsonb, numeric, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

export const productionTasks = pgTable("production_tasks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	work_order_id: uuid(),
	order_id: uuid(),
	space_id: uuid(),
	product_id: uuid(),
	task_no: text(),
	task_type: text().default('process').notNull(),
	task_name: text(),
	task_code: text(),
	product_name: text().notNull(),
	quantity: numeric({ precision: 18, scale:  3 }).default('1').notNull(),
	unit: text().default('件').notNull(),
	length: numeric({ precision: 12, scale:  2 }),
	width: numeric({ precision: 12, scale:  2 }),
	thickness: numeric({ precision: 12, scale:  2 }),
	area: numeric({ precision: 18, scale:  4 }),
	material: text(),
	color: text(),
	process_name: text(),
	completed: numeric({ precision: 18, scale:  3 }).default('0').notNull(),
	status: text().default('pending').notNull(),
	priority: integer().default(0).notNull(),
	progress: text().default('pending').notNull(),
	worker_id: uuid(),
	assigned_to: uuid(),
	assigned_worker_id: uuid(),
	workshop_id: uuid(),
	workstation_id: uuid(),
	wage_rule_id: uuid(),
	estimated_wage_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	final_wage_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	planned_start_date: date(),
	planned_end_date: date(),
	actual_start_date: date(),
	actual_end_date: date(),
	started_at: timestamp({ withTimezone: true, mode: 'string' }),
	submitted_at: timestamp({ withTimezone: true, mode: 'string' }),
	completed_at: timestamp({ withTimezone: true, mode: 'string' }),
	approved_at: timestamp({ withTimezone: true, mode: 'string' }),
	approved_by: uuid(),
	start_date: timestamp({ withTimezone: true, mode: 'string' }),
	end_date: timestamp({ withTimezone: true, mode: 'string' }),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const workerWageRecords = pgTable("worker_wage_records", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	worker_id: uuid().notNull(),
	order_id: uuid(),
	space_id: uuid(),
	product_id: uuid(),
	task_id: uuid().notNull(),
	wage_rule_id: uuid(),
	quantity: numeric({ precision: 18, scale:  3 }).default('1').notNull(),
	unit_price: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	wage_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	status: text().default('pending').notNull(),
	submitted_at: timestamp({ withTimezone: true, mode: 'string' }),
	approved_by: uuid(),
	approved_at: timestamp({ withTimezone: true, mode: 'string' }),
	paid_at: timestamp({ withTimezone: true, mode: 'string' }),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const profiles = pgTable("profiles", {
	id: uuid().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	display_name: text(),
	phone: text(),
	avatar_url: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const customers = pgTable("customers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	name: text().notNull(),
	phone: text(),
	address: text(),
	source: text(),
	status: text().default('active').notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const employees = pgTable("employees", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	user_id: uuid(),
	employee_no: text().notNull(),
	name: text().notNull(),
	phone: text(),
	email: text(),
	avatar_url: text(),
	department_id: uuid(),
	primary_position_id: uuid(),
	employee_type: text().default('full_time').notNull(),
	status: text().default('active').notNull(),
	hire_date: date(),
	leave_date: date(),
	base_salary: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const employeePositions = pgTable("employee_positions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	employee_id: uuid().notNull(),
	position_id: uuid().notNull(),
	is_primary: boolean().default(false).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderSpaces = pgTable("order_spaces", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_id: uuid().notNull(),
	space_no: text().notNull(),
	space_name: text().notNull(),
	space_type: text(),
	sort_order: integer().default(1).notNull(),
	status: text().default('draft').notNull(),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderProducts = pgTable("order_products", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_id: uuid().notNull(),
	space_id: uuid().notNull(),
	product_no: text().notNull(),
	product_name: text().notNull(),
	product_type: text().default('custom').notNull(),
	product_model: text(),
	width: numeric({ precision: 12, scale:  2 }),
	height: numeric({ precision: 12, scale:  2 }),
	depth: numeric({ precision: 12, scale:  2 }),
	area: numeric({ precision: 18, scale:  4 }),
	quantity: numeric({ precision: 18, scale:  3 }).default('1').notNull(),
	material: text(),
	color: text(),
	status: text().default('draft').notNull(),
	quoted_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	cost_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	profit_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	sort_order: integer().default(1).notNull(),
	remark: text(),
	internal_remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderExchanges = pgTable("order_exchanges", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_id: uuid().notNull(),
	from_enterprise_id: uuid().notNull(),
	to_enterprise_id: uuid().notNull(),
	from_user_id: uuid().notNull(),
	status: text().default('sent').notNull(),
	message: text(),
	proposed_changes: jsonb(),
	handled_by: uuid(),
	handled_at: timestamp({ withTimezone: true, mode: 'string' }),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const factoryWorkshops = pgTable("factory_workshops", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	name: text().notNull(),
	factory_code: text(),
	manager: text(),
	location: text(),
	capacity: integer().default(0).notNull(),
	current_load: integer().default(0).notNull(),
	status: text().default('normal').notNull(),
	description: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const wageRules = pgTable("wage_rules", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	rule_name: text().notNull(),
	task_type: text().notNull(),
	process_name: text(),
	unit: text().default('件').notNull(),
	unit_price: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	calculation_method: text().default('by_piece').notNull(),
	role_scope: text(),
	scope_type: text().default('company').notNull(),
	worker_id: uuid(),
	position_id: uuid(),
	product_type: text(),
	extra_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	enabled: boolean().default(true).notNull(),
	created_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const suppliers = pgTable("suppliers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	supplier_code: text().notNull(),
	name: text().notNull(),
	contact_person: text(),
	phone: text(),
	email: text(),
	category: text(),
	rating: text().default('B').notNull(),
	status: text().default('active').notNull(),
	address: text(),
	remark: text(),
	created_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const dealers = pgTable("dealers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	name: text().notNull(),
	contact_name: text(),
	phone: text(),
	region: text(),
	status: text().default('active').notNull(),
	remark: text(),
	created_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const categories = pgTable("categories", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	name: text().notNull(),
	color: text().default('#6366f1').notNull(),
	description: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const notifications = pgTable("notifications", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	task_id: uuid(),
	recipient_id: uuid(),
	type: text().default('assignment').notNull(),
	title: text().notNull(),
	message: text(),
	read: boolean().default(false).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const departments = pgTable("departments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	name: text().notNull(),
	code: text().notNull(),
	parent_id: uuid(),
	sort_order: integer().default(0).notNull(),
	status: text().default('active').notNull(),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const positions = pgTable("positions", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	name: text().notNull(),
	code: text().notNull(),
	department_id: uuid(),
	position_type: text().default('general').notNull(),
	can_receive_production_task: boolean().default(false).notNull(),
	can_calculate_piece_wage: boolean().default(false).notNull(),
	can_review_task: boolean().default(false).notNull(),
	can_assign_task: boolean().default(false).notNull(),
	default_role_code: text(),
	status: text().default('active').notNull(),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const employeeRoles = pgTable("employee_roles", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	employee_id: uuid().notNull(),
	role_id: uuid().notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderPrefixes = pgTable("order_prefixes", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	prefix: text().notNull(),
	name: text().notNull(),
	company_name: text(),
	phone: text(),
	address: text(),
	current_val: integer().default(0).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orders = pgTable("orders", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_no: text().notNull(),
	customer_name: text().notNull(),
	customer_phone: text(),
	customer_address: text(),
	order_source: text(),
	status: text().default('pending').notNull(),
	total_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	cost_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	profit_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	deposit_amount: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	target_factory_id: uuid(),
	dealer_id: uuid(),
	order_flow: text().default('legacy').notNull(),
	from_enterprise_id: uuid(),
	to_enterprise_id: uuid(),
	parent_order_id: uuid(),
	delivery_date: date(),
	remark: text(),
	internal_remark: text(),
	created_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderModules = pgTable("order_modules", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_id: uuid().notNull(),
	module_no: text().notNull(),
	module_name: text().notNull(),
	sort_order: integer().default(1).notNull(),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderItems = pgTable("order_items", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_id: uuid().notNull(),
	module_id: uuid(),
	item_no: text(),
	product_name: text().notNull(),
	specifications: text(),
	woodworking_craft: text(),
	forming_craft: text(),
	painting_craft: text(),
	length_mm: numeric({ precision: 12, scale:  2 }),
	width_mm: numeric({ precision: 12, scale:  2 }),
	thickness_mm: numeric({ precision: 12, scale:  2 }),
	quantity: numeric({ precision: 18, scale:  3 }).default('1').notNull(),
	unit: text().default('件').notNull(),
	color: text(),
	hardware: text(),
	hardware_quantity: numeric({ precision: 18, scale:  3 }),
	construction_surface: text(),
	unit_price: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	subtotal: numeric({ precision: 18, scale:  2 }).default('0').notNull(),
	remark: text(),
	sort_order: integer().default(1).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderItemAttachments = pgTable("order_item_attachments", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_id: uuid().notNull(),
	module_id: uuid(),
	order_item_id: uuid().notNull(),
	file_name: text().notNull(),
	file_path: text().notNull(),
	file_url: text().notNull(),
	file_type: text(),
	// You can use { mode: "bigint" } if numbers are exceeding js number limitations
	file_size: bigint({ mode: "number" }),
	uploaded_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const orderStatusLogs = pgTable("order_status_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	target_type: text().notNull(),
	target_id: uuid().notNull(),
	from_status: text(),
	to_status: text().notNull(),
	changed_by: uuid(),
	changed_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const workOrders = pgTable("work_orders", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	order_id: uuid(),
	factory_id: uuid(),
	workshop_id: uuid(),
	product_name: text().notNull(),
	target_quantity: numeric({ precision: 18, scale:  3 }).notNull(),
	completed_quantity: numeric({ precision: 18, scale:  3 }).default('0').notNull(),
	status: text().default('pending').notNull(),
	priority: text().default('normal').notNull(),
	start_date: timestamp({ withTimezone: true, mode: 'string' }),
	expected_end_date: timestamp({ withTimezone: true, mode: 'string' }),
	actual_end_date: timestamp({ withTimezone: true, mode: 'string' }),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const progressLogs = pgTable("progress_logs", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	work_order_id: uuid().notNull(),
	operator_id: uuid(),
	operator_name: text(),
	action: text().notNull(),
	completed_delta: numeric({ precision: 18, scale:  3 }).default('0').notNull(),
	remark: text(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const workers = pgTable("workers", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	user_id: uuid(),
	worker_no: text().notNull(),
	name: text().notNull(),
	phone: text(),
	gender: text(),
	craft_type: text(),
	workshop_id: uuid(),
	can_receive_production_task: boolean().default(true).notNull(),
	can_calculate_piece_wage: boolean().default(true).notNull(),
	status: text().default('active').notNull(),
	skill_tags: jsonb(),
	hire_date: date(),
	remark: text(),
	created_by: uuid(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const tasks = pgTable("tasks", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	title: text().notNull(),
	description: text(),
	status: text().default('pending').notNull(),
	priority: integer().default(0).notNull(),
	category_id: uuid(),
	assignee_id: uuid(),
	assignee_name: text(),
	assignee_avatar: text(),
	due_date: timestamp({ withTimezone: true, mode: 'string' }),
	completed: boolean().default(false).notNull(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const userSettings = pgTable("user_settings", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	user_id: uuid().notNull(),
	key: text().notNull(),
	value: jsonb(),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});

export const enterpriseJoinRequests = pgTable("enterprise_join_requests", {
	id: uuid().defaultRandom().primaryKey().notNull(),
	enterprise_id: uuid().notNull(),
	user_id: uuid().notNull(),
	status: text().default('pending').notNull(),
	requested_role_code: text(),
	message: text(),
	handled_by: uuid(),
	handled_at: timestamp({ withTimezone: true, mode: 'string' }),
	created_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
	updated_at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
});
